### PR TITLE
Add support for feature equivalent to the SFX Target Precedence option. ...

### PR DESCRIPTION
**Pull request by kevinreiss**
...Supports floating and sinking particular targers to the top of the full-text list. Also adds a miminal test with config values in the test/dummy/umlaut_services.yml file. Also makes related title label configurable. The test here may or may not work. I was unable to get it to run locally. Left it in for the first pull request attempt.

### CODE REVIEW

**Comment by jrochkind** [comment]
The first failure "ResolveControllerTest#test_nytimes_by_issn [/home/travis/build/team-umlaut/umlaut/test/functional/resolve_controller_test.rb:67" is something I've been running into lately, there's something wrong with the test (and/or a bug in Rails 4.2 assert_select stuff), probably not your fault. 

The second failure seems to be you. 

Either way I'll look at this next week, and get it working, and possibly refactor some of the code.

**Comment by jrochkind** [comment]
PS, @kevinreiss , did you notice the `roll_up_prefixes` feature? For how we use the SFX kb, it comes in handy to prevent duplicate listings of slightly different targets that really all go to the same place. Something that could sort of be done in SFX directly with difficulty, but I added to Umlaut to be a lot easier to deal with.

**Comment by jrochkind** [comment]
Also, can you share with me what label you have chosen for your "This version provided from related title" label?  It's possible what you're doing is better and should be made the default anyhow.

**Comment by kevinreiss** [comment]
@jrochkind, yes I'm using the roll_up_prefixes feature. That is definitely useful. I wanted to have the target sorting fire after that routine. Perhaps the 

The label our staff wanted for related titles was https://github.com/pulibrary/umlaut/blob/target_precedence_pul/test/dummy/config/umlaut_services.yml#L26 "May be available under related title" as opposed to the one at https://github.com/team-umlaut/umlaut/blob/master/app/service_adaptors/sfx.rb#L314.

**Comment by jrochkind** [comment]
I'd be happy to just change the default label to what you are using, I think it's probably better (and this feature is a UX sticking point in general; nobody likes how it works, but nobody likes it when it's turned off either). 

I wonder if we should just go with your choice of label for now, and punt on config/i18n. I18n is the right way to do it, but a pain to make work in Umlaut's architecture. 

I like the boost/sink feature. I'd like to enhance it a bit:  

1) Make sure the order you've listed targets in boost/sink is the order they appear in the sorted list too. The top item in your configured boost list should always be above the second, if both are present. 

2) Perhaps support wildcards in boost/sink, boost "EBSCOHOST_*" for example, instead of needing  to list every individual one you might want to boost. 

(These two may interact such that 1 needs to accomodate 2 smartly, of course). 

(Not giving this to you as an 'assignment', I can write that code, or you can, or we can give up on it if neither of us has time for now, heh)

**Comment by kevinreiss** [comment]
Okay, I agree adding options one and two are good ways to go. I'll give it a shot next week [and hopefully get the test suite running locally first!]. If you are okay with our suggested level we can leave hardcoded in the sfx adaptor for now.

**Comment by jrochkind** [comment]
Cool. At any rate, please separate out the 'related title' label from this PR, so this PR can be just about the new feature and they can be considered separately. 

I will try to find time to make sure I have documented correctly how to get tests running on a fresh instance. But I won't try to improve the functionality or fix it so the tests are actually passing, since you say you are working on that. 

Oh wait -- are you trying to point tests at a database that you already created from another application, like an actual local umlaut implementation, not the umlaut sourcecode itself? That won't work. I know because I ran into it. The migrations will have different numberings on the already existing db, so Rails will think you have migrations that haven't run yet, but the changes in those migrations will already have been done in the db.  Create a new db for running tests in umlaut; or delete the contents of the db and let umlaut create it again; or temporarily delete the migrations from umlaut to fool it as a hacky workaround.

**Comment by jrochkind** [comment]
@kevinreiss, I've committed some changes to master to make running tests a bit smoother. 

You would have to merge or rebase your branch on master to get the changes. 

I've also documented the verified process for running tests locally (after the changes made in master) in the wiki: https://github.com/team-umlaut/umlaut/wiki/Developing#running-umlaut-tests

I plan to do some more work in the wiki today or this week to document better some tips and guideance for writing tests, which can be tricky in Umlaut.

**Comment by kevinreiss** [comment]
Thanks @jrochkind. I'll check out the updated docs see if can get the tests running properly. Still hoping to get some time before the end of the week to update this PR.

**Comment by kevinreiss** [comment]
FYI @jrochkind. Smooth sailing using the updated docs on getting tests running locally with the code you recently pushed to master.

**Comment by kevinreiss** [comment]
@jrochkind this only deals with case 1 from your two suggestions:
***
1) Make sure the order you've listed targets in boost/sink is the order they appear in the sorted list too. The top item in your configured boost list should always be above the second, if both are present.
2) Perhaps support wildcards in boost/sink, boost "EBSCOHOST_*" for example, instead of needing to list every individual one you might want to boost.
***
I need to refactor this more to support option 2 above.

**Comment by jrochkind** [comment]
Awesome. Okay, I can also try to work on this if you'd like. Or maybe we don't need case 2 yet, if you don't need it?  Although I'm surprised you didn't need it, I would have, and think I do in the SFX func we're using.  

Can you take out the configurability of the 'related version' label from this PR?  It would need to go in a different separate PR if it was needed, but I think I'll just change the default Umlaut label to what you want for now. Or maybe see if it can be done easily in 18n after all.

**Comment by jrochkind** [comment]
Also something's gone wrong with the way you merged current master into here. The diff for this PR is showing changes against master that should have already been made against master and should not show up as changes. 

I'm not sure what's going on. 

I'm going to make you a committer on the project. If you want to put this in a branch here at team-umlaut/umlaut, it might make it easier for us both to work on it together. Although a `rebase` might be the best solution, but I wouldn't want to do that when you're in the middle of working, because it would confuse your working copy. But maybe you can try a rebase against current master?

**Comment by kevinreiss** [comment]
Okay, let me go through the rebase process again. I had done this before but see I missed a couple of commits you put in on 3/19, and also changed the unit test file substantially so that is probably fouling things up. This feature only changes two files so maybe it might be easier to just re-clone the team-umlaut repo and add the updates to a new branch. The test suite did pass locally for me, not sure what it failed on the jruby environment in travis.

**Comment by jrochkind** [comment]
It might just be github that's doing something weird, maybe your branch is fine. When I do a local checkout of your branch, it doesn't show all the diff with master that github GUI is showing, the local checkout looks right. Confusing! 

The one test failing in JRuby is one that I've been seeing non-deterministically fail for a while now. Soemtimes it passes sometimes it doens't. Something is wrong, but yeah it's got nothing to do with your changes, you can ignore that one.

**Comment by kevinreiss** [comment]
I put up a clean branch containing the changes at https://github.com/team-umlaut/umlaut/tree/sfx_target_ordering.

**Comment by kevinreiss** [comment]
@jrochkind what do you think about closing this PR and resubmitting it from https://github.com/team-umlaut/umlaut/tree/sfx_target_ordering?

**Comment by jrochkind** [comment]
@kevinreiss  Great idea, please!

**Comment by kevinreiss** [comment]
Okay @jrochkind I closed this one out submitted a PR with the the other branch.

**Pull request closed without merging**
