### PR TITLE
Handle no results

### PR DESCRIPTION
**Pull request by ronan-mch**
This is better, but now it's got my gitignore stuff as well!

### CODE REVIEW

**Comment by jrochkind** [comment]
Hi, sorry I didn't attend to this so long, I think I missed it, then got busy, then forgot about it. 

Are you still interested in this?  We might be able to get it into the upcoming Umlaut 4.1 release. 

Can you tell me anything about the context, why this was required for your users?

**Comment by jrochkind** [comment]
I'm worried it might cause problems -- in some cases, nothing can be found in the SFX KB, but Umlaut will still be able to display relevant results, by consulting some of it's other configured sources (Catalog, etc). 

That's the original motivation for the functionality -- the current functionality also matched SFX's own 'citation linker' functionality at the time it was written. I don't know if the 'citation linker' still works that way, but additionally we tried to combine SFX 'citation linker' and 'A-Z' functionality in this one Umlaut feature. 

So I'm a bit worried about the change. 

In general, my current attitude is that it's better to send users to your _catalog_ for journal name searches, not to Umlaut/SFX at all.

**Comment by ronan-mch** [comment]
Hi Jonathan,

If I recall correctly our thinking was is follows, perhaps @knutanton can correct me if I'm misremembering:

In the current situation, if the user searches Umlaut for a journal that Umlaut doesn't have, Umlaut will present the user with a page that resembles a standard journal and a message telling them that this journal is not found in SFX. We think that this is problematic since it gives the user false hope and takes them away from the ability to correct their search. Therefore, we would prefer to give them an error message without taking them away from the search page.

I think we might have a mismatch in terms of our use cases. I don't think we expect our users to use Umlaut to search for anything other than journals. If they are searching for things that are not in SFX but are in our ILS, then we expect them to use our ILS. Again, I'm cc-ing my colleague @knutanton in case I'm misremembering something.

**Comment by jrochkind** [comment]
Cool. We can make it configurable maybe?

**Comment by jrochkind** [comment]
Here, our users definitely use Umlaut for things that aren't journals -- but not the 'search' function, that's just for journals and journal articles. Still, there are journals and journal articles that might not be found in the SFX KB -- and Umlaut will still for instance direct to ILL to obtain that. At least I _think_ there are journals/articles that might not get a match from 'search' function, I forget if 'search' function just includes hits that are _activated_ in KB, or any hit from KB?  If the latter, it would be less likely to not get a hit I guess. 

I'm not sure, it's complicated. So I'm thinking, if you need this, it might make sense to make it configurable?  

Do you have any interest in updating the PR to make sure it still merges with present code, and is configurable? I promise I'll get it merged, hopefully in time for the upcoming 4.1 release.

**Comment by ronan-mch** [comment]
Hi Jonathan,

I'm afraid I won't have time to redo the commit in the near future. I'm happy enough to keep it as a local change for now. If there are others than us interested in the change we can revisit the issue.

Cheers,

Ronan

**Comment by jrochkind** [comment]
No problem @ronan-mch . I might be able to find time to do it myself. 

With you having it as a local change, are you still able to upgrade Umlaut as new versions come out? Or are you on a local Umlaut fork with no easy way to upgrade?  I'd like to help keep everyone on the main Umlaut releases and upgrading easily.

**Comment by ronan-mch** [comment]
Hi, we're still on our local fork. Not sure when I'll get a chance to
upgrade.

ons. 25. mar. 2015 15.06 skrev Jonathan Rochkind <notifications@github.com>:

**Comment by jrochkind** [comment]
Okay, this feature will be in Umlaut 4.1 -- but controlled by new configuration, off by default, but you can get your desired behavior by setting configuration `search.display_zero_hit_results true`. 

So it's there waiting for you!  Thanks for suggesting this change, sorry it took over a year to get it in there.

**Comment by ronan-mch** [comment]
Thanks Jonathan, that's excellent.

On Wed, Mar 25, 2015 at 6:56 PM, Jonathan Rochkind <notifications@github.com

**Pull request merged**
